/// <reference path="modernizr-2.6.2.js" />
/// <reference path="jquery-3.7.0.js" />
/// <autosync enabled="true" />
/// <reference path="../bootdtrap old version for carousel/bootstrap.min.js" />
/// <reference path="../bootdtrap old version for carousel/jquery.min.js" />
/// <reference path="../nicescroll/jquery.nicescroll.iframehelper.js" />
/// <reference path="../nicescroll/jquery.nicescroll.js" />
/// <reference path="ai.0.22.9-build00167.min.js" />
/// <reference path="bootstrap.bundle.min.js" />
/// <reference path="bootstrap.min.js" />
/// <reference path="carousel.js" />
/// <reference path="esm/popper.min.js" />
/// <reference path="esm/popper-utils.min.js" />
/// <reference path="jquery.validate.min.js" />
/// <reference path="jquery.validate.unobtrusive.min.js" />
/// <reference path="jquery-3.4.1.min.js" />
/// <reference path="jquery-3.4.1.slim.min.js" />
/// <reference path="popper.min.js" />
/// <reference path="popper-utils.min.js" />
/// <reference path="respond.js" />
/// <reference path="umd/popper.min.js" />
/// <reference path="umd/popper-utils.min.js" />
